export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || "http://localhost:3000",
  ENDPOINTS: {
    AUTH: {
      SIGNUP: "auth/register",
      SIGNIN: "auth/ambassadorLogin",
      UserData: "users/profile/",
      UserUpdate: "auth/updateProfile",
      AddProducts: "products/create",
      GetProducts: "products/",
      AddUsers: "auth/register",
      UpdateProduct: "products/",
      DeleteProduct: "products/",
      SuspendUser: "users/suspend/",
      ActivateUser: "users/activate/",
      GetUsers: "users/ambassador/",
      UpdateUser: "users/",
      DeleteUser: "users/",
      getTickets: "tickets/user/",
      createTickets: "tickets",
      UpdateTicket: "tickets/",
      ReplyTicket: "tickets/reply/",
      SetPassword: "auth/setPassword/",
      getSales: "payment/",
      getEmail: "reports/",
      getAccountBalance: "account/bank-wallet/",
      createAccount: "account/bank-details/",
      requestWithdrawal: "withdrawal/request/",
      SubmitSale: "promotion/",
      getPromotions: "promotion/",
      getCharts: "sales-chart/ambassador/",
    },
  },
};

export const apiUrl = (endpoint: string) => `${API_CONFIG.BASE_URL}${endpoint}`;
